### ISSUE TITLE
ADDITION REQUEST: Modernization MegaPak

### ISSUE THREAD

**Issue by wyndchyme** [susbaconhairman/minecraft-3ds-unistore#4]
**What would you like to have added to the Store?**
Modernization MegaPak

**What is this content? What does it do?**
An all-in-one modpack containing modernization mods for MC3DS compiled from community work and my own contributions. (pack version 1.0)
Contains: (with credit)
-Cracko298's Enhanced Particles patch
-Cracko298's port of the Mojangles (default Minecraft & MC3DS 1.0) font 
-TheRustico36's Cleann'slick GUI (v3.1) with adjustments made for this pack
-TheRustico36's port of the post-Java 1.19.3 Steve and Alex skins
-Zexlo's port of the post-Java 1.14 villager models and textures
-susbaconhairman's new microSD texture from Vanilla Remastered
-STBUniverse's ports of the Caves & Cliffs Part II and Nether Update panoramas
-STBUniverse's port of the new bat model and textures introduced in Java 1.20.3

Also includes a near-full port of the post-Java 1.14 textures compiled from various sources and texture conversions made specifically for this pack as well as a replacement for the generic dirt background found in MC3DS loading screens

**What type of content is it? World, texture pack, skin(s), mod, misc, etc.?**
Texture pack, skin pack, code.bin, modpack, misc

**Screenshots of the content (240x400 pixel resolution is preferred)**
![2024-08-19_21-34-20 055_top](https://github.com/user-attachments/assets/6989fa27-9561-46e6-9a4c-3c3ce3261004)
![2024-08-19_21-34-20 055_bot](https://github.com/user-attachments/assets/6b85d196-f14d-4a0e-88d4-1f293f8d4ef7)
![2024-08-19_21-31-29 704_bot](https://github.com/user-attachments/assets/3ae1a33f-4e7f-403d-9fd8-549fc4559c6b)
![2024-08-19_21-33-59 938_top](https://github.com/user-attachments/assets/353761ed-177e-4394-b59f-40e082fc3143)
![2024-08-19_21-31-29 704_top](https://github.com/user-attachments/assets/af8e1d44-9f55-49c9-bd76-4f1e0f1a89c4)
![2024-08-19_21-33-59 938_bot](https://github.com/user-attachments/assets/430dc546-a420-48b4-bc03-5e5f4ca244e3)
![2024-08-19_21-32-59 794_top](https://github.com/user-attachments/assets/0b7fd6fa-79dd-4916-8307-76256e10e94c)
![2024-08-19_21-32-59 794_bot](https://github.com/user-attachments/assets/88e597ec-3c31-40ce-bd0f-7ce397ee7ad5)
![2024-08-19_21-32-33 709_top](https://github.com/user-attachments/assets/76aa2639-f7ab-430e-aeca-926c78510298)
![2024-08-19_21-34-57 656_top](https://github.com/user-attachments/assets/a65b1d66-0419-4a37-9571-37bc375af277)

**Icon for the content (48x48 pixel resolution is preferred)**
![pixil-frame-0](https://github.com/user-attachments/assets/ecff008f-a32c-43ac-a9b7-448c3381a51f)

**Repository for the content**
https://github.com/wyndchyme/mc3ds-modern

**Download link for the content**
https://github.com/wyndchyme/mc3ds-modern

**Additional notes**
Thanks to Cracko298, TheRustico36, Zexlo, susbaconhairman, STBUniverse, and other members of the MC3DS modding community.

Also note that the new font may not fit perfectly into some menus, particularly the achievements menu – if you would prefer the MC3DS 1.9 font simply delete the fonts folder included in this pack

**The developers and maintainers of this Unistore may have to modify the content for the store (such as resizing screenshots or changing the content so it may be able to be downloaded properly, etc.)**

**MAKE SURE YOU HAVE READ THE TERMS TO SUBMITTING HERE: https://github.com/Minecraft-3DS-Community/minecraft-3ds-unistore/blob/main/manual.md#requesting-content-to-be-added**

**Comment by susbaconhairman** [comment]
Did you get permission from everyone to use their work in your pack? TheRustico, who made the New GUI, is not mentioned in the credits.
Also, please list everyone, as well as what they "contributed"

**Comment by wyndchyme** [comment]
> Did you get permission from everyone to use their work in your pack? TheRustico, who made the New GUI, is not mentioned in the credits. Also, please list everyone, as well as what they "contributed"

Thanks for the heads-up – TheRustico36's is now credited and the description has been edited to include an in-depth breakdown of who's work is included in this pack and what they worked on

Will see about getting explicit permission to compile these mods in the morning

**Comment by susbaconhairman** [comment]
I will add it to the store.
