### ISSUE TITLE
TAKEDOWN REQUEST: Modernization MegaPak

### ISSUE THREAD

**Issue by wyndchyme** [susbaconhairman/minecraft-3ds-unistore#5]
**What would you like to have removed from the Store?**
Modernization MegaPak v1.0

**Why do you want it removed?**
No confidence in current Minecraft 3DS UniStore administration due to admin's continued erratic behavior (taking down and restoring UniStore seemingly at random, controversy within community, et cetera) which threatens the integrity of this UniStore as well as choice to move to a new UniStore in the foreseeable future

**Does it infringe any copyright? If so, how?**
N/A

**Contact information:**
If you really must, leave a reply to this issue

**Additional notes**
N/A

**MAKE SURE YOU HAVE READ THE TERMS TO SUBMITTING HERE: https://github.com/Minecraft-3DS-Community/minecraft-3ds-unistore/blob/main/manual.md#requesting-content-to-be-added**

**Comment by susbaconhairman** [comment]
I have already repaired my actions, I am willing to unite the community again. Please do not let a few hours worth of drama that;s been repaired by me already ruin the community.

**Comment by wyndchyme** [comment]
> I have already repaired my actions, I am willing to unite the community again. Please do not let a few hours worth of drama that;s been repaired by me already ruin the community.

See "no confidence" in original issue – the integrity of this UniStore and its administration is in question and its continued avaliability is not even remotely guaranteed, as the adminstration's past actions demonstrate. Please remove this pack from the UniStore at your earliest convenience.

**Comment by susbaconhairman** [comment]
I want to have co-ownership in the Unistore, I am willing to repair. If you still don't want you content up, then fine. This may sound hypocritical but removing content splits us even more. I certainly do not want that.

**Comment by susbaconhairman** [comment]
Also, I have tried talking to Vance, he is not willing to repair. He is also not the leader anymore. I would encourage that you don't let him influence your decision.

**Comment by wyndchyme** [comment]
> I want to have co-ownership in the Unistore, I am willing to repair. If you still don't want you content up, then fine. This may sound hypocritical but removing content splits us even more. I certainly do not want that.

Once again, no confidence in the existing administration and I would prefer my pack be hosted on a UniStore with administration that will not use the UniStore as a bargaining chip or take it down at random. Remove this pack at earliest convenience – I would prefer not to ask again.

**Comment by susbaconhairman** [comment]
Fine - I will remove it. But I will say this - this kind of behavior leads way to gatekeeping, which is not good for the community. And again, I am willing to have a co-ownership with the Unistore.
